### ISSUE TITLE
Import/Export - All items w/ cell values reporting "Update" status

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#101]
When going through the import process, the second screen (i.e., item selection screen) is displaying statuses of "Update" for all items containing cell values, regardless of whether those scores have actually been updated since being downloaded.

The "Update" status should only occur when an item's cell values have been modified outside of the system and are different than the scores that existed within the Gradebook immediately prior to initiating the import process.

Items containing scores that, as a whole, match those that currently exist within the Gradebook should return the same "N/A" status as entirely empty items.

**Comment by maurercw** [comment]
@kyleblythe, can you attach an export of the before and then the modified version just so I have an example?  I've got some unit tests that pass and I've done local testing and cannot reproduce easily.
If you export the existing gradebook, and then try to reimport what you just exported without making any changes, does it think they are all updates?

**Comment by maurercw** [comment]
Well, hang on, maybe I can reproduce!  Guess I spoke too soon!

**Comment by maurercw** [comment]
@steveswinsburg, merge PR #111 and see if that fixes it.

**Comment by steveswinsburg** [comment]
Ok that's in. Give it a go.

**Comment by kyleblythe** [comment]
Hi @maurercw,

Just gave this another look, and while it seems that "Update" is no longer displayed when a spreadsheet with no changes is imported (http://www.screencast.com/t/ZelvRCsNo), the issue is still occurring as soon as any change is made to any item in the spreadsheet.

Here is a screenshot of the unchanged spreadsheet file:
http://www.screencast.com/t/c75Itwuwt7

I then modified scores only within "Week 1 Part". When importing back into the system, this should be the only item with a status of "Update." Screenshot:
http://www.screencast.com/t/ObLMEhY2

However, this is the resulting status screen:
http://www.screencast.com/t/WSgewg73r

All items with any scores attached to them report an "Update" status, while only empty items show "No Changes."

**Comment by maurercw** [comment]
Oops!  I'll take another look.

**Comment by maurercw** [comment]
@kyleblythe My first pass is unable to reproduce.  Any chance Excel is changing values on you?  The export might have a .0 at the end of the grades...maybe Excel is dropping that off?  I'll try a bit more though.

**Comment by maurercw** [comment]
Yeah, I think that might be it.  I opened one of my exports in excel and just saved it without making any other changes and it converted a whole bunch of stuff.  Removed quotes (probably a non-issue) and dropped any .0 from scores.  So, maybe a question is should the .0 be in the export at all?  Are the scores just integers?  Looking into that a bit...

**Comment by kyleblythe** [comment]
Hi @maurercw ,

Ah, I think that's it! Yep, we should not be using decimal places in the export format (unless an existing score explicitly had a decimal in place e.g., 72.8). We should default to integers, both because excel definitely auto-formats .0 to a standard integer, and because it matches the formatting of the Gradebook grades screen, which doesn't display .0's.

**Comment by steveswinsburg** [comment]
The scores are stored as doubles (ie decimals) however in the UI we just strip the .0 via `StringUtils.removeEnd(grade, ".0")` so I reckon just do that. Is a score of say 12.3 treated ok or is that also modified by excel?

**Comment by maurercw** [comment]
@steveswinsburg Please see PR #133.

**Comment by steveswinsburg** [comment]
Nice one, verified.
