### ISSUE TITLE
"Undefined" Value Being Added to Cell Entries When Selecting "Enter" Too Quickly

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#102]
When quickly entering grade data into the interface, if the "enter" key is pressed too quickly (i.e., before the edit state has fully loaded), the typical "enter" behavior does not occur. Rather than saving the score and navigating to the cell below, an additional value of "undefined" is entered into the cell, immediately following whatever keyboard input was provided before.

Example: 70undefined

**Comment by steveswinsburg** [comment]
Fixed in #107
