### ISSUE TITLE
"Back" Behavior in Import/Export Not Displaying Items on Item Selection Page

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#103]
When navigating pas the item selection screen during the Import Export Process, if the "Back" button is pressed, returning to that second screen leads to the following bug:

Instead of displaying all items, only the items that were check-marked previously appear:
http://www.screencast.com/t/SpAtrcNh4C

The only way to display all items again is to reset the tool and start over.

**Comment by maurercw** [comment]
Does the checked status of the item need to be retained, or just make sure that the full list is displayed?

**Comment by maurercw** [comment]
@steveswinsburg, please merge PR #113 to see if this takes care of the issue.  I've got the full list rendering, but it doesn't re select the items you previously had checked.  Is that ok?

**Comment by steveswinsburg** [comment]
Ok thats in. I think just showing all items would be ok for now. @kyleblythe can you pls confirm?

**Comment by kyleblythe** [comment]
Confirmed - looks good!

**Comment by steveswinsburg** [comment]
Thanks for the confirmation kyle, looks good from here too. Closing! :+1:
