### ISSUE TITLE
"LDAP Timeout" Runtime Exception Error Message

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#104]
Randomly when loading the GB or navigating between screens in the Gradebook, an LDAP Timeout Runtime Exception error message occurs.

The following occurred when completing the Import/Export process:
http://www.screencast.com/t/tQsJuNmhzI

The following occurred when logging out of Sandboxclasses1, logging back in, and trying to enter the new Gradebook tool:
http://www.screencast.com/t/iMORGUYih

**Comment by steveswinsburg** [comment]
Have you got this error again? This come from the LDAP provider, most likely surfaced through a call to getUser. I havent checked this hypothesis, but that may be a RuntimeException which we can explicitly catch and maybe retry the call. It's not an error in the GB code though.

**Comment by steveswinsburg** [comment]
I've received this error on the NYU sandbox servers before, in other tools, so I'm going to close this one as its not gradebook specific. @kyleblythe if you guys havent seen it, I may be able to reproduce and then one of the NYU guys can look through the logs.
