### ISSUE TITLE
Additions to Import/Export

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#105]
The following are proposed additions to the Import/Export process:

~~**1. Item Selection Screen - Merging of Grade Item and Comments into Single Grouping**
Items and comments are currently displayed as separate importable items on the 2nd Import screen. Merge these together into a single grouping, with line breaks between groupings. The item and comment should still occur on separate lines, with separate statuses associated with each for clarity. Provide only one check-box for each grouping, so that one is importing both the item and its associated comments.~~

**2. Visual Distinction of Update/New Items**
Provide a visual cue making it easier to tell the Updated/New items apart from current "N/A" items (e.g., make "N/A" items styled in a lighter font w/ italics).
**EFFORT:** low

~~**3. Change "N/A" Item Status to "No Changes"**~~

~~**4. Change "NEW" Status to "New"**~~

~~**5. Remove "N/A" Point Value for Comments**
Leave this field blank.~~

**6. Provide Check-Box Filter to Only Display Updated/New Items**
While the default display on the 2nd Import screen will continue to mirror, in descending order, that of the left-to-right spreadsheet order, provide a check-box filter above the items that will allow users to hide all N/A/No Changes items from the view, effectively showing only Update/New status items.
**EFFORT:** high

**7. Check the last update date of the imported file and present a warning if it’s older than X days.**
If this is possible, present a warning immediately following upload notifying users that the file has not been updated in x days.
**EFFORT:** low

**8. Concurrency Check Mechanism**
When grades are being applied we need to use the concurrency check mechanism. The Import code will need to pull the grades and do the comparison. Otherwise you could be setting on the import page for a while, grades could be changed by someone else and then you overwrite the grades with the import. Handle this elegantly, maybe taking the user back to the checkbox page.
**EFFORT:** medium

**9. Updated Comment Title Format in Downloadable Spreadsheet File and Include Warning on Default Item Creation Page**
Simplify the current comment title format in the GB download file (e.g., */ Week 2 Part */ ) to instead use a single asterisk at the beginning (e.g., \* Week 2 Part ). Additionally, provide a warning when user tries to add an asterisk at the beginning of normal item creation via the GB interface, notifying them that this format is reserved exclusively for importing GB comment columns (Note: possibly even in the gradebook service?).
**EFFORT:** medium

**10. Confirmation Screen - Add Point Total Info**
Provide item point totals on the final confirmation screen, mirroring the info available on item selection screen.
**EFFORT:** medium

**11. CSV Download - Template Format When GB Does Not Contain Items**
When the Gradebook does not contain any items, the CSV download should instead provide a template for instructors, with a sample item column and sample comments column. If not modified, these sample columns should not be imported when uploading back into the system.
**EFFORT:** ?

**12. Additional Export Options (to match those available in the "Course Grades" screen of GB1)**
When exporting the GB on the Import / Export screen, provide a text link below the "Download" button entitled "Advanced Options." Selecting this will open a lightbox window that allows users to customize what is included in the export, and select a .pdf export format. The defaults ("Student Name," Student ID," "Gradebook Item Scores" and "Gradebook Item Comments") will be selected and appear at the top. Additional options will be available below, and will include:
- Last Log Date
- Course Grade
- Calculated Course Grade
- Grade Override

(Note that, in GB1, there's also a selectable option for "Points," which will display the total course grade in points. To make this more straightforward, let's have the "Course Grade" option here just export whichever final course grade the instructor's chosen to display for them in the spreadsheet view?)

When any of these options are selected/de-selected and modified from the default, text should be highlighted informing the user that this export can not be imported back into the Gradebook.

Mockup:

![2015-08-19_10-22-12](https://cloud.githubusercontent.com/assets/11447474/9358890/5d0fb5ea-465c-11e5-9d19-dc5126e26f87.png)

**EFFORT:**?

**12. Disable checkbox for items with a status of "No Changes"**
Since no action will occur when selecting "No Changes" items for import, disable the checkboxes for these items.

**Comment by maurercw** [comment]
Are these just wish list items and not bugs that need to be addressed?  I've actually taken care of item 1 already in some refactoring I just did (PR #126).

**Comment by steveswinsburg** [comment]
Hi @maurercw yep you can leave these ones for the time being and we'll get the bugs nailed. Cheers!

**Comment by steveswinsburg** [comment]
Hi @kyleblythe, I've committed a fix for 3,4 and 5 on this list. I can confirm that 1 is implemented too (thanks @maurercw).

To make it easier to see what is outstanding I've edited your original issue and added a strike through for those implemented, plus triaged the other issues to L/M/H effort. Cheers.

**Comment by kyleblythe** [comment]
Updated issue to include requirement for additional export options (as per GB tech call on 8/13).

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1356
