### ISSUE TITLE
When grouped by category, "Move Left" and "Move Right" changes standard order

### ISSUE THREAD

**Issue by payten** [steveswinsburg/gradebookNG#108]
To replicate:
1. have more than two categories and more than 2 grade items per category
2. click "Group by Category"
3. open the menu for a grade item  and click "Move Right" (or "Move Left")
4. Page refreshes
5. Grade item has been moved right in non-categorised mode
6. click "Group by Category" again
7. Grade item has not been moved to the right of its category sibling

**Comment by steveswinsburg** [comment]
The move left and move right only change the order within the gradebook service. Sounds like this also needs to call the reorder method for the category?

**Comment by payten** [comment]
Yeah exactly.  So when "Group by Category" is checked, the link needs to hit the other endpoint.  As this is currently a Wicket link, is there a way the Javascript can tell it to take into account the category scope?

**Comment by steveswinsburg** [comment]
The checkbox click would probably need to fire a request to the backend, and we can stick this in the session state. This 'group by category' is not persistent right?
