### ISSUE TITLE
Check comments come through from external gradebook items

### ISSUE THREAD

**Issue by steveswinsburg** [steveswinsburg/gradebookNG#115]
Ensure the comments are coming through for the gradebook items that come from external sources, eg Assignments

**Comment by kyleblythe** [comment]
Hi @steveswinsburg,

To confirm:

Assignments
When originating from the Assignments tool, comments (entered as instructor notes) are passed back to the GB. They are not editable within the GB.

When not originating from the Assignments tool (associated with existing GB item), comments are NOT passed back to the GB. They are editable within the GB, but do not get reflected within the Assignments tool.

Forums
Must be created in GB and then associated with Forum/Topic. Comments are passed back to the GB and are editable in both locations.

Tests & Quizzes
Must originate from T&Q. Comments are not passed back to the GB and are not editable within the GB.
