### ISSUE TITLE
Add error messages at top of table with "view details"

### ISSUE THREAD

**Issue by jeffpasch** [steveswinsburg/gradebookNG#120]
When there are errors on the page, display error message above the grading table with the following:
- X no. of errors on this page
- "View details"
- Expanding "view details" will show (1) the location of each error using coordinates (i.e., user and item) and (2) the reason for error (e.g., concurrent edit). The coordinates of the error should be a link, which will take the user to that cell in the table (to address the error).

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1358
