### ISSUE TITLE
Provide error details in cell

### ISSUE THREAD

**Issue by jeffpasch** [steveswinsburg/gradebookNG#122]
Allow user to view error details by clicking on (or hovering over) the error icon in a cell. Clicking should bring up a small window overlaying the table with error message detail. 

If error is because value is simply not saved (e.g., user has connectivity issues) serve message of "grade not saved"

If error is caused by concurrent edit, display information about who updated the cell and when. Details for this in a separate Issue, https://github.com/steveswinsburg/gradebookNG/issues/121

**Comment by payten** [comment]
I think this was delivered previously with the enhancements to the cell popover notifications.

Currently there's one generic error message when something stops the grade from saving (not taking into account the concurrency check).  @steveswinsburg, @jeffpasch, are there any particular backend exceptions we would like a descriptive error message for?

**Comment by jeffpasch** [comment]
I believe we decided in the last call that one generic error message is ok. They'll get the info on who else is editing via the pencil icon

**Comment by jeffpasch** [comment]
I believe we decided in the last call that one generic error message is ok. They'll get the info on who else is editing via the pencil icon
