### ISSUE TITLE
Add the permission page

### ISSUE THREAD

**Issue by steveswinsburg** [steveswinsburg/gradebookNG#131]
Gradebook _classique_ had a rule based permission page, not a standard permission helper style page.
This allows building a set of rules for individual graders.
This needs to be implemented.

From looking through the code, it looks like there is API code to be ported too as its currently only handled in the GradebookManager...

![screen shot 2015-06-27 at 9 29 17 am](https://cloud.githubusercontent.com/assets/129129/8389125/0471ad20-1caf-11e5-9192-ba8f259f478a.png)
![screen shot 2015-06-27 at 9 29 04 am](https://cloud.githubusercontent.com/assets/129129/8389127/04b23ade-1caf-11e5-9a5f-004cdc3a6995.png)
![screen shot 2015-06-27 at 9 26 29 am](https://cloud.githubusercontent.com/assets/129129/8389128/05061a28-1caf-11e5-84bb-289b493730e8.png)
![screen shot 2015-06-29 at 9 42 20 pm](https://cloud.githubusercontent.com/assets/129129/8407219/ccf6a4e0-1ea7-11e5-8863-691e8eb7af4f.png)

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

We're seeing the following "Something went wrong" error message when testing these permissions from the TA's view:

http://www.screencast.com/t/saKaD6rr

**Comment by payten** [comment]
Regarding the "Something went wrong", I've created an issue that has some more details #205.

I've also added some styles to the form and the TA's EID to the dropdown as per today's call #207.

**Comment by steveswinsburg** [comment]
Ok I'm going to close this and work on the bug in #205. #207 merged.
