### ISSUE TITLE
"Percentage" Grade Entry Type

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#146]
Provide the ability to enter grades as percentages into the spreadsheet interface, if the "Percentage" grade entry type is selected in the GB settings.

If the "Percentage" grade entry type is selected:
- Remove the " / [total points]" element that appears within the cell when editing it.
- Add a " % " into the cell when it is being edited.
- If the cell value is empty/null, keep the cell empty. However, once a value has been entered, provide a " % " after the value in the cell (e.g., 90% instead of 90).

**Comment by steveswinsburg** [comment]
For reference, Gradebook _classique_ has percentage grade precision to 2 decimal places (12.34%) and points grade precision of 1 decimal place (eg 12.3).

**Comment by steveswinsburg** [comment]
The setting works, need to follow through the logic flow as it returns the concurrent error, presumably it’s using the point grade underneath, so that needs to be made aware. Also need some UI work to make it show percentage in the cell. Cells probably also need to be aware of the setting.

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1363
