### ISSUE TITLE
column headers for student info columns not fixed

### ISSUE THREAD

**Issue by jeffpasch** [steveswinsburg/gradebookNG#16]
column headers for student info columns should stay fixed. 
http://note.io/19vWMO7

**Comment by payten** [comment]
Hi @jeffpasch. Hm yeah.. that's my doing.  It's a little trickier to do this with the current <table> markup and then also include the accessibility suggestions from TPG. 

I'll spend more time on it to see if I can work it through.  Just to confirm, which columns should be fixed?

Also, do we need the table header to be fixed? Or just the left-side columns?  It'd be technically a lot simpler if only one set of elements needed to be fixed.

**Comment by jeffpasch** [comment]
Hey @payten. Our thought was to have left three columns fixed -- Student, Section/Group, and Course Grade. (Section/Group isn't in the grid yet.)  And, just to make life difficult, we were also hoping to freeze the header row as well. In terms of priority for the webinar next week, I think freezing the left columns might be more important...although I realize the choice of which to do right now may also be driven by technical realities.

**Comment by payten** [comment]
Gotcha - of course you want everything :)  Maybe I'll focus on the fixed columns for the demo -- it also seems the fixed headers don't really have too much impact as we're only displaying 8 items in the table.

**Comment by jeffpasch** [comment]
Well I know how you like a challenge. ;) And yeah, I agree that for the demo fixed headers won't have an impact.

**Comment by steveswinsburg** [comment]
I think we are good here. Closing this one off.

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1333
