### ISSUE TITLE
Red error message sometimes remains at top with no text

### ISSUE THREAD

**Issue by jeffpasch** [steveswinsburg/gradebookNG#165]
It looks like this: https://www.evernote.com/l/AI3X093PmE1LaZkJ1aR0IwjDUNnTZTwi6VE

One way to replicate is to generate an error in a cell, then enter more than enter a value over the amount of points in another cell.

Or get an error then just refresh the page.

**Comment by steveswinsburg** [comment]
<img width="1023" alt="screen shot 2015-07-31 at 7 07 27 am" src="https://cloud.githubusercontent.com/assets/129129/8995130/e2f786e2-3752-11e5-9429-8ffc2cc07467.png">
