### ISSUE TITLE
Add support for gradebook.coursepoints.displayed for student view

### ISSUE THREAD

**Issue by steveswinsburg** [steveswinsburg/gradebookNG#167]
If `gradebook.coursepoints.displayed = true`, have an option in the settings page that allows the instructor to toggle on/off the course grade as points.

Likewise, add a setting for the percentage grade display.

The backend will need to check this setting and get the appropriate course grade. The front end will then need to render the appropriate columns.

**Comment by kyleblythe** [comment]
In Settings, beneath the option to "Display Course Grade to Students Now," provide a series of checkboxes for instructors to select which course grade options will display to students. 

By default, "Letter" and "Percentage" will be selected, though the instructor can modify this. Additionally, the "Points" option will be available, if categories and weighting have not been enabled within the GB.

**Comment by kyleblythe** [comment]
Below the "Display Course Grade to Students Now" option, provide text stating "Display Grade As:" followed by:
- Letter Grade
- Percentage
- Points

Points will only be available to select if Categories/Categories & Weighting is NOT enabled within the Gradebook.

Letter Grade and Percentage will both by default be selected. Instructor can modify this by deselecting checkboxes, or enabling others. Any combination of the 2/3 (depending on setup) will be allowed.

If the instructor deselects ALL checkboxes, a red warning should appear notifying them that at least one display option must be selected.

Additionally, to the right of "Display Course Grade to Students Now," provide a preview pane showing how the selected options will appear to students.

Mockup:

![course grade display settings](https://cloud.githubusercontent.com/assets/11447474/10521326/4265386a-733d-11e5-9ec8-29cbcbb14be1.png)

**Comment by steveswinsburg** [comment]
Hey @kyleblythe, 

The gradebook record in the database contains columns for `course_grade_displayed`, `course_points_displayed` and `course_average_displayed`. Interestingly, `course_average_displayed` is completely unused at present, it is never set or retrieved anywhere, as far as I can see.

The mappings I see for this are:
1. 'Display course grade to students now' = `course_grade_displayed`. This is already wired up and cannot be changed.
2. 'Letter Grade' = There is no field to store this.
3. 'Percentage' = we could use the `course_average_displayed` - see below.
4. 'Points' = `course_points_displayed`. Maps fine, no further discussion required.

**Problems**
For Letter Grade, there is no field to store this. We will need to add it, which means a db conversion. Until now we have been able to avoid this...

For Percentage, we could use the course_average_displayed as it is currently unused, however I am unsure of the original intent of this field and whether it is meant to be student specific or entire site specific. In any case it is unimplemented so maybe we can just use it. It kind of fits since it is the same naming as the course_points_displayed field.

Thoughts?

**Comment by kyleblythe** [comment]
Hey @steveswinsburg ,

Sorry for the delay in responding. Hmm, yeah. Do you see any way around having to add a new field to the db? In the past, when the grade released to students was both the letter grade & percentage, what field was storing those entries? Was that just part of the course_grade_displayed (sorry my understanding's so basic)?

That's interesting that the course_average_displayed is currently unused. I wonder what it was meant for in GB1? Students cannot see the class average for any items in the GB, only their individual subtotal averages across categories, so unless that's tied to category subtotal scores I'm not sure what this could have meant in relation to them. Mapping "Percentage" to this db field wouldn't interfere with any of the class-wide averages we're planning to include in the instructor's "View Grade Statistics" lightbox, would it?

**Comment by steveswinsburg** [comment]
In GB1, toggling 'display course grade to students now' adjusted `course_grade_displayed` and controlled the letter grade/pass not pass etc.

So the one setting controlled both the actual display of the course grade AND the letter/pass grade.

In addition, if the sakai.property `gradebook.coursepoints.displayed = true` was set, then there is an additional column in the course grade page for points. This is a server wide setting.

Discussed on the call today, not a big deal to add a new column for controlling letter grade, then we can have this flexible. So the `course_grade_displayed` will only control if the course grade is displayed, not what is displayed. 

In terms of backwards compatibility, GB1 will ignore this and continue to show the letter grade or not depending on the setting.

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1367
