### ISSUE TITLE
Course Grade Display Type - Instructors and TAs

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#168]
Within the "Course Grades" column header in the spreadsheet view, provide an option for "Course Grade Display Type."

This should open a lightbox window that will allow for instructors and TA's (if given the ability to see course grades) to be able to determine what displays within the course grades column.

By default, "Letter" and "Percentage" should be selected, though the user can modify this. A third option, "Points" should be available for selection only if categories and weighting have not been enabled within the GB. Explanatory text should also be provided, notifying the user that this display type is only for them, and that the student course grade display type is available, along with the course grade release option, in Settings.

Ideally, this display type will be set on a user-by-user basis.

**Comment by kyleblythe** [comment]
![2015-07-31_13-58-14](https://cloud.githubusercontent.com/assets/11447474/9013805/387a36bc-378c-11e5-9642-415994f511fb.jpg)

**Comment by kyleblythe** [comment]
Follow-up re: formatting and alignment of these grade values when displayed for the instructor/TA in the spreadsheet view:

Ordering of displayed grades should be as follows:
1. Letter Grade
2. Percentage
3. Points

Formatting of the displayed grades should be as follows:

A-   92%  276/300

Additionally, there should be consistent alignment following the letter grade to aid with visual clarity, since some letter grades will have a +/- afterwards, while others will not.

Example:

A___95%
A-__ 92%
B+__91%

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1368
