### ISSUE TITLE
Course Grade Override & Log

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#169]
Within individual students' Course Grade cells, provide a drop-down menu containing options for a) Grade Override, and b) Override Log.

For Grade Override:

Provide a lightbox window, wherein the instructor may see the course grade info for the selected student (same as the current "Course Grades" screen in GB1), as well as provide a course grade override. Additionally, provide the ability to navigate to the previous/next student.

![2015-07-31_14-03-50](https://cloud.githubusercontent.com/assets/11447474/9013918/fdc79748-378c-11e5-92d2-39b4537bbb92.jpg)

For Override log:

Provide an override grade log lightbox window, similar to the grade logs for individual item cells.

**Comment by kyleblythe** [comment]
Additional details re: Grade Override:

To allow flexibility / precision for override grade entry, ideally we could provide multiple entry fields within the "Grade Override" column - one for letter grade entry (with + / - capability), one for percentage grade entry, and one for points (if using the standard GB setup or unweighted categories. This should be unavailable / hidden if using Categories & Weighting).

When a grade is entered into one of these fields, automatically provide a corresponding entry into the additional fields. Examples:
- If entering an "A" into the letter grade field, the percentage field would automatically populate with the corresponding default percentage for "A" as calculated in the GB, i.e., 95%.
- The percentage could then be tweaked to provide an exact grade. If the grade is changed to a score outside of the letter grade's range, provide an updated letter grade. Changing the grade to 97%, for example, would cause the letter grade to remain an "A", while changing the percentage grade to 91% would change the letter grade to "A-."

This relationship could be represented graphically by a link icon / lock icon, as seen when modifying the size of images in applications like photoshop:

http://www.screencast.com/t/wGwOPNzDs9jo

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1369
