### ISSUE TITLE
Column and cell dropdown behavior with scroll and clicking out

### ISSUE THREAD

**Issue by jeffpasch** [steveswinsburg/gradebookNG#173]
Column and cell dropdown behavior can stick a around a bit longer than needed. To replicate:
1. click on cell or column header dropdown. Click into another cell. > dropdown menu remain.
2. scroll left to right and menu is floating around like a champ.
3. click into edit mode of another cell and then out of edit mode and it seems to go away.
4. click on another column header and it also seems to go away.

https://www.evernote.com/l/AI0zV6EHxNZANbihvSLC2zjdtpu2QNS5X6E

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1371
