### ISSUE TITLE
Validation/Warning Message for "Set Score for Empty Cells"

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#177]
Provide data validation for the "Set Score for Empty Cells" screen, preventing users from accidentally supplying an invalid (e.g., negative number or letter/symbol) score that would affect multiple cells.

Additionally, if the user supplies a score in this field that is in excess of the item's maximum points, provide a lightbox warning/confirmation window that users must interact with in order to continue:

> The supplied score is in excess of the maximum point value for this Gradebook item. Do you want to continue?
> Cancel / Continue

**Comment by payten** [comment]
I've had a go at this one.  If the mechanism for showing the close confirmation modal on the student drilldown popup doesn't make you vomit then I'll submit a PR with a similar implementation for this stuff: https://github.com/steveswinsburg/gradebookNG/compare/master...payten:set-score-validations

**Comment by steveswinsburg** [comment]
Yeah I reckon the popup is good. Go for it!

**Comment by kyleblythe** [comment]
Loving it.

The extra-credit pop-up that appears at present seems to load above the original lightbox:

![2015-09-09_14-47-07](https://cloud.githubusercontent.com/assets/11447474/9771088/c7a858ac-5701-11e5-9390-0a1e9e655b1d.png)

Can we get this popup to load on top of the existing lightbox (like the close confirmation for the "Student Review Mode")?

Additionally, it looks like invalid entries can still get applied; they just don't get loaded upon the page refresh. Can we implement a similar lightbox for invalid entries?

**Comment by kyleblythe** [comment]
Hi @payten ,

Looks like the popup is loading behind the original "Set Score for Empty Cells" lightbox:

![2015-09-17_11-36-01](https://cloud.githubusercontent.com/assets/11447474/9937828/6070a6a0-5d30-11e5-8b07-c0fdfb78fddd.png)

**Comment by kyleblythe** [comment]
Confirmed.
