### ISSUE TITLE
Permissions Screen - Course Grade Visibility Checkbox

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#178]
Introduce new checkbox in the permissions screen that grants explicit visibility access for final course grades based off the section permissions granted to the TA.

This checkbox option ("Allow TA to see course grade for selected section(s) below") can appear once an initial rule is added on the permissions screen. It can sit above the rules themselves, and will be by default selected.

This option, when checked, will grant course grade visibility for any sections listed in the rules below.

**Comment by steveswinsburg** [comment]
Checkbox is done and permissions are saved, just need to hook this into the actual display of the course grade.

**Comment by steveswinsburg** [comment]
This one should be ok to test now. The TA should get a - instead of the course grade when viewing.

**Comment by kyleblythe** [comment]
Confirmed!
