### ISSUE TITLE
Resize Student Name and Course Grade Columns

### ISSUE THREAD

**Issue by jeffpasch** [steveswinsburg/gradebookNG#184]
Give more room for name and stack "Course Grade" header text. Note that we'll eventually need to fit letter grade, Percentage to 2 decimal places and letter grade.

**Comment by steveswinsburg** [comment]
Done in #190.

**Comment by payten** [comment]
Not working in Firefox:

<img width="1306" alt="screen shot 2015-08-21 at 10 56 30 am" src="https://cloud.githubusercontent.com/assets/608337/9399141/81fa1524-47f3-11e5-9c1b-6b6227b2947d.png">

**Comment by jeffpasch** [comment]
yup looks good in Chrome, FF, and Safari now.
