### ISSUE TITLE
Cell/table related bugs

### ISSUE THREAD

**Issue by payten** [steveswinsburg/gradebookNG#185]
- ~~Grades do not seem to getting saved enter grade, then refresh~~ #192
- For EC, if you reenter the same score, the + does not come up.
- when popover in last few rows, need to scroll down to see it.
- warning icon appearing in items originating from other tools - possible to treat entire cell as clickable button for popover?
- “Delete” option appearing for item originating from other tool
- Cell dropdown tight with comments bubble

**Comment by payten** [comment]
All fixed in PR #182. 

Re:  "warning icon appearing in items originating from other tools" -- we need to retain the icon as all popovers are now on the icon. So I've replaced the warning icon with a locked icon and styled it so it doesn't stand out too much.

**Comment by kyleblythe** [comment]
These are all looking good. The only one that still seems to be occurring is the first bullet ("Grades do not seem to getting saved enter grade, then refresh"). The GB still seems to be referring to a specific state (e.g., "?132"), which won't display saved grades when the page reloads. A refresh of the tool itself fixes it.

**Comment by payten** [comment]
Thanks @kyleblythe - I conveniently missed that one!  I've created a new issue for that bug: #192.

**Comment by payten** [comment]
Closing as only remaining bug has been pulled into its own issue #192.
