### ISSUE TITLE
Category Subtotals/Course Grades are Reflecting "Null" Values

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#196]
Category subtotal percentages (within the subtotal columns/student summary/student view and when calculated in the Course Grade) are reflecting null values, calculating them as 0's.

E.g., A category contains two items, each worth 100 pts. Student receives a 90/100 on one item, with no value supplied to the second. Category subtotal should display as 90% (90/100), but is instead displaying as 45% (90/200).

GB1 ignores null values in order to give subtotal/course grade calculations based solely off of entered grades.

**Comment by steveswinsburg** [comment]
I have a fix for this just testing it out.

**Comment by steveswinsburg** [comment]
This is fixed in https://github.com/sakaiproject/sakai/pull/1029, awaiting a build check then will be merged.

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

Looks great. The subtotals are now ignoring null values. Thanks!

![2015-09-03_13-54-48](https://cloud.githubusercontent.com/assets/11447474/9666339/6e1e1ee2-5243-11e5-8613-9fe27e412057.png)
