### ISSUE TITLE
Show/Hide Items Slowness When Dealing with Entire Categories/Many Students

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#197]
There is slowness when showing/hiding items when there are many students (and therefore many cells) in place.

There are also delays when showing/hiding entire categories of items.

**Comment by payten** [comment]
After profiling the JavaScript with a Gradebook containing 13 items and 100 students, I noticed that when hiding or showing all columns it took around 2 seconds to complete the action with much of the time being spent refreshing the summary, visual cue and fixed table header.

To fix, I've changed the JavaScript to only refresh these dependant components once if multiple columns are being toggled in the single action.  This reduced the 'hide all' time to ~200ms.

Delivered in PR #206.

**Comment by kyleblythe** [comment]
Looks good! This issue can be closed.
