### ISSUE TITLE
Restrict ability to apply extra credit items to an extra credit category

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#198]
When creating a GB item, if an extra credit category is selected for the item, prevent the "Extra Credit" checkbox from being selectable for the item, thereby restricting both the item and the category from being extra credit at the same time.

**Comment by steveswinsburg** [comment]
Done. Ready for testing. Requires SAK-29883

**Comment by kyleblythe** [comment]
Looks good!
