### ISSUE TITLE
Drop-down menus no longer opening

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#208]
Drop-down menus within cells/column headers no longer appear upon selecting the drop-down icon.

**Comment by payten** [comment]
Hm.. it looks like there's been a core change to include the Bootstrap framework by default (see https://github.com/sakaiproject/sakai/commit/fdb93118007d631885790039b344624cfd40c750).  I imagine that's conflicting with our own.  I think we'll will need to remove our own inclusion of Bootstrap and hope that doesn't break anything too much!

**Comment by kyleblythe** [comment]
Hi @payten ,

The drop-downs are now appearing again, which is great. Quick formatting bit that I noticed - with the new native bootstrap, drop-down options are now appearing as underlined. Can we remove this formatting to clean up the drop-downs?

![2015-09-02_11-16-57](https://cloud.githubusercontent.com/assets/11447474/9635443/89ae6732-5164-11e5-9902-52e8efaa4a0f.png)

**Comment by kyleblythe** [comment]
Looks good!
