### ISSUE TITLE
Assignment modification functions are available to a TA

### ISSUE THREAD

**Issue by steveswinsburg** [steveswinsburg/gradebookNG#210]
Modification functions like editing, moving and deleting assignments are available to a TA via the column header dropdown. They don't do anything but they should be suppressed.

<img width="612" alt="screen shot 2015-09-07 at 11 18 30 pm" src="https://cloud.githubusercontent.com/assets/129129/9717543/f8a5645a-55b6-11e5-8aee-047c593d2e45.png">

**Comment by steveswinsburg** [comment]
Also the Add Gradebook Item button.

**Comment by steveswinsburg** [comment]
OK, the whole menu is hidden unless instructor. Likewise for add gradebook item. The permission restrictions can be relaxed a bit when the grade stats go in and if we want TA's to access any of this.

**Comment by kyleblythe** [comment]
This looks good. Can revisit once the section awareness for "Set Score for Empty Cells" / "Grade Statistics" options are in place.

**Comment by steveswinsburg** [comment]
Closing for now to reduce the noise.
