### ISSUE TITLE
Add TA permission handling for view/grade permissions within the cells

### ISSUE THREAD

**Issue by steveswinsburg** [steveswinsburg/gradebookNG#211]
Permissions are complete however the rules need to be applied to the rendering of the cells.
Perhaps this can be attached into the grade item when rendering the matrix.

**Comment by steveswinsburg** [comment]
Current design thinking is that after fetching the gradesdefinition and when iterating it, if TA, perform a lookup here to determine if user can grade. Backend call to lookup the VIEW or GRADE permission for student and item, taking in account grades and categories and add to the GbGradeInfo.

**Comment by steveswinsburg** [comment]
PR #264 is in so this should now be resolved.

**Comment by kyleblythe** [comment]
Looking good. Only outstanding issue with regards to TA grade/view permissions is #270 . Closing this one.
