### ISSUE TITLE
Ability to clear a score

### ISSUE THREAD

**Issue by payten** [steveswinsburg/gradebookNG#218]
Hi @kyleblythe, @jeffpasch, @steveswinsburg,

I was wondering if there's a requirement for an instructor to clear a score?  We currently allow a score to be zero or a positive number, but I noticed in the old gradebook you could remove a score by clearing the input field and clicking Save Changes.  

I can imagine a case where an instructor wants to clear a bunch of scores before applying the "Set Scoresfor Empty Cells"... or perhaps clearing out a mistake to leave the cell blank.

**Comment by jeffpasch** [comment]
Ah right. I hadn’t noticed that. Yeah, I think we’ll need to allow for that. An instructor could start to enter a bunch of scores in a column then realize they’ve entered for the wrong gradebook item. 

I think they’d try to delete these values as they would in excel or google sheets—by highlighting the cell and simply hitting the delete key. Or they’d click into the cell to edit and remove the value. Ideally we’d want to be able to delete with either method.

---

Jeff Pasch
LMS Product Director
ITS .edu Services
New York University

## 212.992.7555

**Comment by payten** [comment]
Thanks @jeffpasch.  I think we can easily support the "click to edit and remove value" mechanism.  The "hitting delete key" might require a custom endpoint (please correct if I'm wrong @steveswinsburg) as the Wicket editable label needs the input to be present before the update can be performed -- basically the cell is readonly and only becomes editable once Wicket pulls in the input field when the user clicks on it.  

I've had a quick play to get the click-edit-then-remove-value mechanism working.  Will hold off on PR until we discuss tomorrow - https://github.com/steveswinsburg/gradebookNG/compare/master...payten:allow-clearing-of-score

Regarding the "delete key" mechanism, upon detecting a delete key we might be able to line up some custom javascript to perform the activation of the input field, clear the field then post the field.. feels dirty so will hold off exploring that one.

**Comment by steveswinsburg** [comment]
I reckon its ok as a first slice if the grader needs to edit each cell to
remove the grade. We can handle this really simply when checking if a grade
was sent.
Longer term we could probably support the delete key mechanism, perhaps we
should raise onto the backlog for future work for that feature.

**Comment by kyleblythe** [comment]
Confirmed!
