### ISSUE TITLE
Section Awareness for "Set Score for Empty Cells," with persistent confirmation message

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#226]
Provide section awareness for the "Set Score for Empty Cells" functionality in GB items, allowing for scores to be applied to empty cells on a section-by-section (or group-by-group) basis. A new drop-down menu within the "Set Score for Empty Cells" lightbox will allow for instructors/TAs to choose the section/group for which to apply scores (with, in the case of TAs, this being restricted by the sections/groups for which they have grade access).

A new confirmation message will appear any time a score is set, notifying users of the score that is being applied and what section(s)/group(s) to which the score is being applied.

For Instructors:
- When viewing the Gradebook by All Sections/Groups, selecting "Set Score for Empty Cells" will open the lightbox. The drop-down within will be set, by default, to "All Sections/Groups."
- When filtering by a given section/group, selecting "Set Score for Empty Cells" will open the lightbox. The drop-down within will be set, by default, to the section/group by which they are currently filtering. This can be modified by selecting the drop-down.

For TAs:
"Set Score for Empty Cells" will be restricted only to sections/groups for which the TA has "Grade" permissions. If they have "grade" access for multiple sections/groups, apply the same capabilities as above.

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1376
