### ISSUE TITLE
"Edit Item Details" as a lightbox window

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#235]
When "Edit Item Details" is selected for a GB item, have the resulting open in a lightbox window instead of a new window.

**Comment by steveswinsburg** [comment]
Good news @kyleblythe, this is now done :+1: 
I think the build is frozen at an earlier commit though, so I'll add the label and just get around to it when you can.

**Comment by kyleblythe** [comment]
Confirmed.
