### ISSUE TITLE
Dynamic Updating of the Course Grade / Cat Subtotal Column Values

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#239]
As scores are entered into the GB, live-update the values for category subtotal percentages and the Course Grade column.

**Comment by payten** [comment]
Hi @steveswinsburg, I've had a quick go at this, but a little unsure of the best-practice Wicket way of doing things:

https://github.com/steveswinsburg/gradebookNG/compare/master...payten:magic-course-grades

Works a treat!  But storing the labels on the GradebookPage context feels a little strange...Let me know if I'm on the right track and I'll prepare a PR.

**Comment by payten** [comment]
After doing some reading, we could be able to do this using the Wicket event bus and broadcasting a custom event when a score is updated.  The course grade and category average cells can override onEvent and check for the custom event and if the studentuuids match, then update themselves.  I'll look into this next week.

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1379
