### ISSUE TITLE
Disable "Include in course grade calc" checkbox when item is not assigned to category

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#242]
When creating (or editing) a GB item, disable the "Include in course grade calculations" checkbox if a category has not been selected for the item. Once a category is selected, enable the checkbox.

**Comment by payten** [comment]
Just to confirm, does this behaviour only apply when the Gradebook has been setup with "Categories & Weightings"? Or should it apply also when "Categories Only" is selected?

**Comment by payten** [comment]
If the original Gradebook is to believe, then we want to disable the "Include in course grade calculations" checkbox when category is empty for both "Categories Only" and "Categories & Weightings".

**Comment by kyleblythe** [comment]
Confirmed
