### ISSUE TITLE
Additional rules appear after saving TA permissions

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#250]
Upon entering and saving permissions for a TA, the resulting screen refresh w/ save confirmation shows an additional rule tacked on below the existing rules. It looks like the the "Add rule" box gets automatically selected, which will result in a "Can View All Categories in All Sections/Groups" rule  appearing beneath the existing rules. Selecting "Clear change" will remove this.

http://www.screencast.com/t/VSTFacEt

**Comment by steveswinsburg** [comment]
Confirmed, if the checkbox to view course grade is checked.

**Comment by steveswinsburg** [comment]
This should now be fixed. Accidentally referenced 211 so it won't show up here :sob:

**Comment by kyleblythe** [comment]
Confirmed
