### ISSUE TITLE
When invalid score is entered, keep score in field and direct users to refresh page to see last saved

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#252]
When an invalid score is saved (resulting in the triangle "warning" message), retain the invalid score in the field along with the warning message. This allows the user to see what score is causing the error message. Within the possible warning messages, provide additional text notifying the user to refresh the tool in order to see the last saved score.

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1380
