### ISSUE TITLE
Revisit the "Group by Category" setting

### ISSUE THREAD

**Issue by payten** [steveswinsburg/gradebookNG#260]
From the 10/8/2015 team call.

Currently the "Group by Category" button state is stored on the user's session, such that resetting the tool will return this value to false.  

I think we have a few options:

1) Persist the setting to the site properties so resetting the tool retains the state
2) Default the "Group by Category" to ON if the Gradebook has categories, that way resetting the tool will return the state to ON if was turned OFF.
3) Both 1) and 2)

**Comment by kyleblythe** [comment]
Confirmed. As per #265, when categories are enabled, the tool defaults to "Group by category" and reverts upon tool reset.
