### ISSUE TITLE
Ability to get a course grade for a single student regardless of whether course grades are released

### ISSUE THREAD

**Issue by payten** [steveswinsburg/gradebookNG#266]
Required for #247.  

In dynamically updating a student's course grade when a score changes, the current endpoint returns 'null' if the course grades are configured to be _not_ released to students.  It'd be great to have the ability to pull back the latest course grade for a single student, also formatted accordingly to the Gradebook settings.

**Comment by steveswinsburg** [comment]
Checked out the service code for this. There is a hard check in there to not do anything if its not released. However we can probably bypass that with a role check. We'll need this bypassed for both instructor and TA correct?

**Comment by payten** [comment]
Yep that sounds right - the course grade column is visible to both instructors and TAs so that makes sense.

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1383
