### ISSUE TITLE
Ability to get a category average for a single student and single category

### ISSUE THREAD

**Issue by payten** [steveswinsburg/gradebookNG#267]
Required for #247.  

In dynamically updating a student's category average when a score changes, currently simplest way is to hit `buildGradeMatrix`, which may not be the most efficient method.  It'd be great to have the ability to pull back the latest category average for a single student and a provided category ID.

**Comment by steveswinsburg** [comment]
Yeah we can make a new method here that calls:

`gradebookService.calculateCategoryScore(final Long categoryId, final List<Assignment> viewableAssignments, final Map<Long,String> gradeMap);`

We'll need to do a couple of lookups to get the assignment list and grademap but that is probably ok.

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1384
