### ISSUE TITLE
When TA’s have view permissions, they should not see “Edit comment” in comment popups

### ISSUE THREAD

**Issue by steveswinsburg** [steveswinsburg/gradebookNG#268]

**Comment by steveswinsburg** [comment]
Hey Payten, this is in the popoverpanel and the link is in the HTML, not controlled via Wicket. May need to pass the gradeable flag into it (available in the GradeItemCellPanel where the popover is constructed) and then hide that link with a div/span WebMarkupContainer around the html link.

**Comment by kyleblythe** [comment]
Confirmed.
