### ISSUE TITLE
TA view - some cells not editable with grading permissions in place

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#270]
In columns for which TA has grading access, if the cell has no grade associated with it, the TA cannot edit the cell to provide scores. Additionally the cell following one with no grade associated with it also cannot be edited.

![2015-10-22_10-26-27](https://cloud.githubusercontent.com/assets/11447474/10668230/4e67be82-78a9-11e5-9e53-7c1329dcc653.png)

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1385
