### ISSUE TITLE
Keyboard navigation issues

### ISSUE THREAD

**Issue by payten** [steveswinsburg/gradebookNG#273]
From team call:
1. when tabbing from the dropdown menu, close it
2. why doesn't the dropdown menu link have a nice blue outline like other elements? (Chrome)

**Comment by payten** [comment]
Re: 2) well, it turns out it's a Bootstrap feature! or bug.. whichever way you want to argue it: `https://github.com/twbs/bootstrap/issues/14939`

While we can't get the "nice blue outline", I'll look into improving the styles so focus/active states are more distinct.

**Comment by kyleblythe** [comment]
Confirmed.
