### ISSUE TITLE
Make category header text always visible when scrolling

### ISSUE THREAD

**Issue by payten** [steveswinsburg/gradebookNG#274]
For wide category header cells, the category text can be scrolled off the page while the category item cells are still visible.  It'd be nice if the category text magically moved within the header cell to be visible as the horizontal scroll changes.

**Comment by kyleblythe** [comment]
Hi Payten,

This is looking great, and I love the automatic scrolling. I did like how, before, the text was centered within the category header. Right now it looks like it's justifying to the left. Is it possible to have it justify to the center of whatever space in the category header row is visible? E.g.,

![image](https://cloud.githubusercontent.com/assets/11447474/11128864/6c2012a6-894a-11e5-92ea-1e195cea450f.png)

**Comment by payten** [comment]
Next build should pick this up... so much magic/mathematics!  :confounded:

**Comment by kyleblythe** [comment]
Beautiful!
