### ISSUE TITLE
GB Throwing Runtime Exception Errors

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#276]
Gradebook is currently throwing the following runtime exception error in every test site:

![image](https://cloud.githubusercontent.com/assets/11447474/10776369/2d81962e-7ce7-11e5-8122-ee191fe84838.png)

**Comment by payten** [comment]
@steveswinsburg, this looks related to the new settings database column.  The column we had Andy create was `course_grade_letter_displayed` (from the Oracle script) but the SQL in the error refers to `course_letter_grade_displayed`.. eep.

**Comment by steveswinsburg** [comment]
Fixed, sorry about that!
