### ISSUE TITLE
Slowness when saving grades & entering grade "edit" mode

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#281]
As per our GB call last week, there seems to be some pretty noticeable slowness when both saving grades and entering the edit mode for a cell.

Saving scores for a cell is taking approximately 1.27 seconds to complete when categories & weighting are enabled - this may have to do with the live category subtotal score calculation. Perhaps it's possible to do this subtotal calculation on the side (or after the score is successfully saved), so that there's no delay for the user.

Entering the edit mode for a cell is also experiencing slowness (~600ms in Canberra, ~90ms in NY/Pittsburgh). Example of edit mode slowness taken from Shanghai:
http://screencast.com/t/8DufgNGzs2j

**Comment by kyleblythe** [comment]
Additional notes:

PG: Locally for me it takes ~80ms to load the input and then 640ms to post the change.  Without the triggering the ScoreChangedEvent (to populate the Category Avg, Course Grade) the post takes 120ms.  So, definitely overhead in calculating those values.. add latency and makes for a sad faces.

PG: I investigated an alternative mechanism for the table inputs when looking into touch-screen compatibility: https://github.com/steveswinsburg/gradebookNG/issues/151 - that might come in handy to at least remove the first GET/latency to turn the label into an input field.

**Comment by steveswinsburg** [comment]
Sounds like it's the category/course grade calc on every cell update that is causing the slowdown - this should be made asynchronous, perhaps a callback/behaviour on the appropriate cells (category/course grade) so it can update itself in the background. It would mean that a user could tab to the next cell and continue on, then the other cell would update itself when ready.

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1388
