### ISSUE TITLE
Refactor categorized sort order code to use Wicket events

### ISSUE THREAD

**Issue by payten** [steveswinsburg/gradebookNG#285]
To improve the robustness and reduce complexity of the categorized sort order mechanism, we should look to refactor the existing code to use Wicket events.  The problem is, we need to keep the sort order XML in sync with the state of the gradebook.  This includes when grade items are added, removed or moved to a new category; or when categories are enabled, disabled, added or removed.  Wicket events seem like a good fit to broadcast when these changes happen and callbacks can ensure the XML is in sync.

Relates to #282.

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1389
