### ISSUE TITLE
Drag reorder not sticking with browser refresh

### ISSUE THREAD

**Issue by payten** [steveswinsburg/gradebookNG#35]
Hi @steveswinsburg,

After dragging and dropping a column I've been noticing the sort order isn't sticking on a page refresh, however when I hit the tool reset action the new sort order applies.  Smells of caching?

Cheers
Payten

**Comment by payten** [comment]
Hm.. looks like there's a similar issue when entering a grade too e.g. I enter a new grade value; after refresh of page it reverts to the previous value; after reset of tool it displays the new value.

**Comment by steveswinsburg** [comment]
Interesting. The wicket models are updating but the page refresh is pulling the current version of the page from the cache due to the ?pageid param being in the URL. Investigating.

**Comment by steveswinsburg** [comment]
Ok so we can add a different rendering strategy which seems to fix this. The only thing is it makes the URLs a bit ugly.

getRequestCycleSettings().setRenderStrategy(IRequestCycleSettings.RenderStrategy.ONE_PASS_RENDER); 

It's in but commented out in the Application class. Let me know your thoughts.

**Comment by steveswinsburg** [comment]
I think I might leave this as a known issue for now. This adds some ugly bits to the URL. There are a few ways to fix this so we can look at in in depth soon.

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1336
