### ISSUE TITLE
Enhance student summary

### ISSUE THREAD

**Issue by steveswinsburg** [steveswinsburg/gradebookNG#66]
As an instructor, when you click on the student summary, the screen should default with everything visible. There will then be an option to go into student review mode where its just for the student. When leaving the student review mode, warning that things will become visible again.

**Comment by kyleblythe** [comment]
When clicking on a student's grade summary, the lightbox window that opens should provide the following:

Default view - "Instructor View"
- In the default view, all content behind the lightbox remains visible.
- All grades/items should be visible, regardless of their release state.
- Iconography from the item column should be represented, denoting EC, unreleased, not included in grade calc.
- Text should denote if course grade is not visible to students.
- Ability to navigate to previous / next student.

![2015-07-31_10-12-02](https://cloud.githubusercontent.com/assets/11447474/9017668/20602a0e-37a6-11e5-9f69-e4989de9ef83.jpg)

"Student View"
- Once in Student View, background becomes opaque.
- Should reflect student's view, with unreleased grades/items not appearing.
- If an item in a column is not released, the category subtotal grade should be hidden.
- No ability to navigate to previous / next student.

![2015-07-31_10-12-46](https://cloud.githubusercontent.com/assets/11447474/9017744/62e09eb8-37a6-11e5-9bfa-8483d0445a87.jpg)
- If exiting the Student View, provide a warning message.

![2015-07-31_10-13-13](https://cloud.githubusercontent.com/assets/11447474/9017748/7513088c-37a6-11e5-89f6-29b7f43d217e.jpg)

**Comment by payten** [comment]
Hi @steveswinsburg - just bouncing this one to you for some help.  The last requirement for this modal is a confirmation popup when closing the Wicket window, as per:

> ...is it possible to introduce an additional confirmation lightbox window that opens on top of the "Student Review" mode when you try to exit out, letting you know that you're about to surface other students' grades?

Happy to hack at it if you can point me in the right direction!

**Comment by kyleblythe** [comment]
Hi @payten ,

Looks great. I made a few add'l notes in #186 .

**Comment by steveswinsburg** [comment]
Cool I think we can close this one. More stuff tracked in #186.

**Comment by steveswinsburg** [comment]
This one was unable to be migrated.
