### ISSUE TITLE
Introduce grade log / comment functionality in cells

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#91]
Provide the functionality available in the GB cell dropdown menu: Grade Log, and Comments.

Grade Log:

Once "Grade Log" is selected, display the following grade log as a modal window, displaying all grade values that have been supplied for that cell, with a timestamp and netID for the instructor who supplied the grade.

![grade log 1](https://cloud.githubusercontent.com/assets/11447474/7772084/fde40a36-0069-11e5-9e59-8fda43999b53.jpg)

If the grade cell is empty and no entries have yet been provided, supply default text where the grade values would be, stating "No grades have been entered for this cell."

Comments:

If no comments have been entered yet for a cell, the drop-down menu option should read "Add Comment." If a comment currently exists, it should read "Edit Comment." In either case, selecting this option will open a new modal window containing a text field. If a comment had already been supplied, the text of the comment will be populated in this field.

![comment 1](https://cloud.githubusercontent.com/assets/11447474/7772069/e0cefb72-0069-11e5-9493-deaa5e6a9955.jpg)

Once a comment has been supplied, a comment icon will appear in the upper-right of the applicable cell (above the cell drop-down arrow). Clicking this icon will open a drop-down menu displaying the cell's comment, along with an "Edit" option.

![comment 2](https://cloud.githubusercontent.com/assets/11447474/7772064/c60acad2-0069-11e5-8ab1-cab0e7662e25.jpg)

**Comment by steveswinsburg** [comment]
Grade log is in. Comments next.

**Comment by steveswinsburg** [comment]
Hey @payten , I've added in a has-comment class to the cells when they have comments. This is also dynamically added if you add a comment to a cell without a comment.

Could we add that comment icon that we discussed for the cells that have the has-comment class?

**Comment by steveswinsburg** [comment]
OK the wicket code should be done, assigned to @payten for the styles 👍

**Comment by steveswinsburg** [comment]
Styles are done. The only thing not implemented here is the hover on the comment bubble and the ability to edit. We'll see how this goes with feedback before implementing
