### ISSUE TITLE
Section/Group filter

### ISSUE THREAD

**Issue by payten** [steveswinsburg/gradebookNG#98]
Hi @steveswinsburg,

Just thought I'd add an issue for this feature.

I was going to jump in and have a go at implementing this via the Javascript, but quickly realised we haven't surfaced any of the user memberships in the DOM yet.

Is there a way we can get all the user's memberships quickly?  Or should we perhaps load all the group membership data in asynchronously?

Thanks,
Payten

**Comment by steveswinsburg** [comment]
IIRC I have a stub for this in the backend. I think the question is after a group is selected,  is it a backend call to then filter the users? I think it would need to be, unless we get it all initially and serialize it into the Dom? There could be many groups for every student though...

**Comment by payten** [comment]
Yep cool, that works for me.  Would that filter be passed through to the service to perform the filter there?  Or would we just filter the complete matrix once we have it?

**Comment by steveswinsburg** [comment]
Two options I can think of:
1. And probably simplest for now: Pass back to the backend with the filter then rebuild the matrix with just the matching users. 
2. Returning the list of groups for each user as part of the matrix, but then serialise the groups into a data attribute on the user. Filtering would then be client side. Could add a lot of data into the dom.

Need to think about preserving the filter when modal window callbacks fire that update the page / move left right (which currently refresh). Maybe stick it in the session.

WDYT?

**Comment by steveswinsburg** [comment]
I think I'll do option 1 and store the current filter in the session. This would then match with the way I'm doing the sorting of the assignment grades where that flag also needs to be stored in the session. There will be a DTO that can be serialised that we can stick these bits and pieces into.

**Comment by payten** [comment]
Ah cool - I was wondering to serialise those things.  I'd started to feel out 1) but had trouble attaching the group filter to the matrix listing/DataTable.  I'm still learning Wicket and the intricacies of it all.  Thanks for picking it up.

**Comment by payten** [comment]
In regards to retaining state on page refreshes, I guess we have a few options:
- store the state on the session and maintain this state via the wicket filters plus some custom javascript to reestablish the state in the browser
- try to avoid page refreshes and let the browsers retain the state where possible

At the moment much of the state is established in the browser and we avoid page refreshes by AJAX'ing POSTs and GETs as required.  I understand that may not be possible with the group/section filter and sorting, so to keep the interface consistent upon these page refreshes we may need to store many of these things on the session.  Ideally we'd store which columns are visible, whether categories are enabled, perhaps the currently focused cell and any current error/info messages.  

Potentially the custom javascript could control all of the state stuff using cookies and querying those cookies upon initialising the page and each of the features.  For me the question is which parts should Wicket handle and where can the custom javascript best pick up the slack.

**Comment by steveswinsburg** [comment]
I'm going to give it a crack with the session state, bearing in mind we
don't want to bloat the session. It will be pretty similar to what you
described, fetching it from session right at the beginning and loading it
in. I can dump that into a DOM attribute if the JS will need it. Will see
how I go.

**Comment by steveswinsburg** [comment]
To finish this off we need to hook up the sections/groups to the session state and the matrix builder. On to it.

**Comment by steveswinsburg** [comment]
This is now complete. High five very nice. :+1:

**Comment by payten** [comment]
Works great! :fireworks:

**Comment by steveswinsburg** [comment]
Awesome

sent from my mobile device
